site_name: Bernardo Stearns Blog
site_url: https://berstearns.github.io/
docs_dir: src
site_dir: docs

theme:
  name: material
  favicon: assets/luffyfavicon.ico
  palette:
    scheme: dracula
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

extra_css:
  - assets/css/dracula.css

plugins:
  - search
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      categories_allowed:
        - General
        - Papers
        - Learning
  - tags
  - markmap:
      base_path: mindmaps
      encoding: utf-8
      file_extension: .mm.md
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
